---
- name: Create a backup for a VM
  hosts: localhost
  connection: local
  tasks:
    - name: include vars
      include_vars:
        dir: group_vars

    - name: New bckup for a VM
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: "{{ datacenter }}"
        template: "{{ item }}"
        name: "{{ item }}-12-02-20"
        folder: /01 System/Backup_manual
        state: poweredoff
        networks: []
        disk: []
        datastore: "{{ datastore }}"
      with_items: "{{ serverlist }}"
