---
- name: Creating a domain user
  hosts: ad
  tasks:
  - name: include vars
    include_vars:
      dir: group_vars

  - name: Ensure user is present
    win_domain_user:
      name: "{{ item }}"
      password: 1qazXSW@
      state: present
      groups:
        - Users
    with_items: "{{ userlist }}"
